mc_shop_static_page_view:
    path:     /{slug}/read
    defaults: { _controller: McShopStaticPageBundle:Default:index }

mc_shop_static_page_new:
    path:     /new
    defaults: { _controller: McShopStaticPageBundle:PageCrud:new }

mc_shop_static_page_edit:
    path:     /{slug}/edit
    defaults: { _controller: McShopStaticPageBundle:PageCrud:edit }

mc_shop_static_page_remove:
    path:     /{slug}/remove
    defaults: { _controller: McShopStaticPageBundle:PageCrud:remove }

mc_shop_static_page_list:
    path:     /list
    defaults: { _controller: McShopStaticPageBundle:PageCrud:list }
