# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    access_denied_url:    ~ # Example: /foo/error403
    providers:
        user:
            entity: { class: McShop\UserBundle\Entity\User }
        in_memory:
            memory: ~
    role_hierarchy:
        ROLE_USER:       ROLE_USER
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|bundles)/
            security: false
        main:
            anonymous:    true
            pattern: ^/
            form_login:
                provider:   user
                login_path: mc_shop_user_login
                check_path: mc_shop_user_login
                always_use_default_target_path: false
            logout:
                path: mc_shop_user_logout
            remember_me:
                secret:   '%secret%'
                lifetime: 604800
                path:     /
            switch_user:  true
    encoders:
        McShop\UserBundle\Entity\User:
            id: md5salted_encoder
    access_control:
        - { path: ^/(ru|en)/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/(ru|en)/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/(ru|en)/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
