mc_shop_finance_sendForm:
    path:     /{amount}/form
    defaults: { _controller: McShopFinanceBundle:Payment:sendForm }

mc_shop_finance_interraction:
    path:     /interraction.html
    defaults: { _controller: McShopFinanceBundle:Payment:interraction }
    methods: [POST]

mc_shop_finance_fail:
    path:     /fail.html
    defaults: { _controller: McShopFinanceBundle:Payment:fail }
    methods: [POST]
